package com.github.skanga.ajent.tools.catalog;

public enum ToolKind {
  READ, EDIT, WRITE, BASH, GREP, GLOB, LIST_DIR, TODO, WEB_FETCH, WEB_SEARCH,
  FIND_DEFINITION, DIAGNOSTICS, GIT_STATUS, GIT_DIFF, GIT_LOG, GIT_COMMIT,
  REMEMBER, FORGET, WIPE, TASK, SKILL, SEARCH_DOCS, REPO_MAP
}
